# Generated by Django 4.1.6 on 2023-02-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_instalador_divida_alter_instalador_total_av_and_more'),
        ('falcao', '0006_delete_vendas'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instalador')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falcao.produtos')),
            ],
        ),
    ]
