# Generated by Django 4.1.6 on 2023-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='produto_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='falcao/media')),
                ('descricao', models.TextField()),
                ('custo', models.FloatField(default=0)),
            ],
        ),
    ]
