# Generated by Django 4.1.6 on 2023-03-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcao', '0007_produtos_custo'),
        ('administrador', '0003_produto_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='produtos',
        ),
        migrations.AddField(
            model_name='vendas',
            name='produtos',
            field=models.ManyToManyField(to='falcao.produtos'),
        ),
    ]
