# Generated by Django 4.1.6 on 2023-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_remove_vendas_produtos_vendas_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produto_admin',
        ),
        migrations.AddField(
            model_name='admin',
            name='valor_vendas',
            field=models.FloatField(default=0),
        ),
    ]
