# Generated by Django 4.1.6 on 2023-03-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcao', '0007_produtos_custo'),
        ('administrador', '0005_delete_produto_admin_admin_valor_vendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='produtos',
        ),
        migrations.AddField(
            model_name='vendas',
            name='produtos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='falcao.produtos'),
            preserve_default=False,
        ),
    ]
