# Generated by Django 4.1.6 on 2023-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_remove_vendas_produtos_vendas_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor_venda',
            field=models.FloatField(default=0.0),
        ),
    ]
