# Generated by Django 4.1.6 on 2023-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='instalador',
            name='sobrenome',
        ),
    ]
