# Generated by Django 4.1.6 on 2023-02-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_instalador_nome_remove_instalador_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.estado')),
            ],
        ),
        migrations.AddField(
            model_name='instalador',
            name='cidade',
            field=models.ManyToManyField(to='accounts.cidade'),
        ),
    ]
