# Generated by Django 4.1.6 on 2023-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cidade_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalador',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='cidade',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
        migrations.AddField(
            model_name='instalador',
            name='cidade',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
