# Generated by Django 4.1.6 on 2023-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_instalador_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalador',
            name='divida',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='instalador',
            name='total_av',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='instalador',
            name='total_vendido',
            field=models.FloatField(default=0),
        ),
    ]
