# Generated by Django 4.1.6 on 2023-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
