# Generated by Django 4.1.6 on 2023-02-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falcao.produtos')),
            ],
        ),
    ]
