# Generated by Django 4.1.6 on 2023-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcao', '0006_delete_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='custo',
            field=models.FloatField(default=0),
        ),
    ]
